cosmo/src/main/java/org/osaf/cosmo/model/Item.java
/*
 * Copyright 2007 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.osaf.cosmo.model;

import java.util.Date;
import java.util.Map;
import java.util.Set;

/**
 * Represents an item on server.  All
 * content in cosmo extends from Item.
 */
public interface Item extends AuditableObject{

    /**
     * Return all stamps associated with Item.  Use
     * addStamp() and removeStamp() to manipulate set.
     * @return set of stamps associated with Item
     */
    public Set<Stamp> getStamps();

    /**
     * @return Map of Stamps indexed by Stamp type.
     */
    public Map<String, Stamp> getStampMap();

    /**
     * Add stamp to Item
     * @param stamp stamp to add
     */
    public void addStamp(Stamp stamp);

    /**
     * Remove stamp from Item.
     * @param stamp stamp to remove
     */
    public void removeStamp(Stamp stamp);

    /**
     * Get the stamp that corresponds to the specified type
     * @param type stamp type to return
     * @return stamp
     */
    public Stamp getStamp(String type);

    /**
     * Get the stamp that corresponds to the specified class
     * @param clazz class of stamp to return
     * @return stamp
     */
    public Stamp getStamp(Class clazz);

    /**
     * Get all Attributes of Item.  Use addAttribute() and 
     * removeAttribute() to manipulate map.
     * @return
     */
    public Map<QName, Attribute> getAttributes();

    public void addTicket(Ticket ticket);

    public void removeTicket(Ticket ticket);

    public void addAttribute(Attribute attribute);

    /**
     * Remove attribute in default namespace with local name.
     * @param name local name of attribute to remove
     */
    public void removeAttribute(String name);

    /**
     * Remove attribute.
     * @param qname qualifed name of attribute to remove.
     */
    public void removeAttribute(QName qname);

    /**
     * Remove all attributes in a namespace.
     * @param namespace namespace of attributes to remove
     */
    public void removeAttributes(String namespace);

    /**
     * Get attribute in default namespace with local name.
     * @param name local name of attribute
     * @return attribute in default namespace with given name
     */
    public Attribute getAttribute(String name);

    /**
     * Get attribute with qualified name.
     * @param qname qualified name of attribute to retrieve
     * @return attribute with qualified name.
     */
    public Attribute getAttribute(QName qname);

    /**
     * Get attribute value with local name in default namespace
     * @param name local name of attribute
     * @return attribute value
     */
    public Object getAttributeValue(String name);

    /**
     * Get attribute value with qualified name
     * @param qname qualified name of attribute
     * @return attribute value
     */
    public Object getAttributeValue(QName qname);

    /**
     * Set attribute value of attribute with local name in default
     * namespace.
     * @param name local name of attribute
     * @param value value to update attribute
     */
    public void setAttribute(String name, Object value);

    /**
     * Set attribute value attribute with qualified name
     * @param key qualified name of attribute
     * @param value value to update attribute
     */
    @SuppressWarnings("unchecked")
    public void setAttribute(QName key, Object value);

    /**
     * Return Attributes for a given namespace.  Attributes are returned
     * in a Map indexed by the name of the attribute.
     * @param namespace namespace of the Attributes to return
     * @return map of Attributes indexed by the name of the attribute
     */
    public Map<String, Attribute> getAttributes(String namespace);

    public Date getClientCreationDate();

    public void setClientCreationDate(Date clientCreationDate);

    public Date getClientModifiedDate();

    public void setClientModifiedDate(Date clientModifiedDate);

    public String getName();

    public void setName(String name);

    /**
     * @return Item's human readable name
     */
    public String getDisplayName();

    /**
     * @param displayName Item's human readable name
     */
    public void setDisplayName(String displayName);

    public User getOwner();

    public void setOwner(User owner);

    public String getUid();

    public void setUid(String uid);

    public Set<CollectionItem> getParents();
    
    /**
     * Each collection an item belongs to contains additional
     * attributes, and is represented as a CollectionItemDetails object.
     * @param parent parent collection
     * @return details about parent<-->child relationship
     */
    public CollectionItemDetails getParentDetails(CollectionItem parent);

    /**
     * Return a single parent.
     * @deprecated
     */
    public CollectionItem getParent();

    /**
     * Transient attribute used to mark item for deletion.
     * @return true if item should be deleted
     */
    public Boolean getIsActive();

    /**
     * Transient attribute used to mark item for deletion.
     * @param isActive true if item should be deleted
     */
    public void setIsActive(Boolean isActive);

    /**
     * Get all Tickets on Item.  
     * @return set of tickets
     */
    public Set<Ticket> getTickets();

    public Set<Tombstone> getTombstones();

    public Item copy();

}

cosmo/src/main/java/org/osaf/cosmo/model/NoteItem.java
/*
 * Copyright 2007 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.osaf.cosmo.model;

import java.io.Reader;
import java.util.Date;
import java.util.Set;

import net.fortuna.ical4j.model.Calendar;

import org.osaf.cosmo.hibernate.validator.Task;

/**
 * Extends {@link ICalendarItem} to represent a Note item.
 * A note is the basis for a pim item.
 */
public interface NoteItem extends ICalendarItem{

    // Property accessors
    public String getBody();

    public void setBody(String body);

    public void setBody(Reader body);

    public Date getReminderTime();

    public void setReminderTime(Date reminderTime);

    /**
     * Return the Calendar object containing a VTODO component.
     * @return calendar
     */
    @Task
    public Calendar getTaskCalendar();

    /**
     * Set the Calendar object containing a VOTODO component.
     * This allows non-standard icalendar properties to be stored 
     * with the task.
     * @param calendar
     */
    public void setTaskCalendar(Calendar calendar);

    public Set<NoteItem> getModifications();

    public void addModification(NoteItem mod);

    public boolean removeModification(NoteItem mod);

    public void removeAllModifications();

    public NoteItem getModifies();

    public void setModifies(NoteItem modifies);

}

cosmo/src/main/java/org/osaf/cosmo/model/User.java
/*
 * Copyright 2007 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.osaf.cosmo.model;

import java.util.Set;

/**
 * Represents a user in the cosmo server.
 */
public interface User extends AuditableObject{

    /**
     */
    public static final String USERNAME_OVERLORD = "root";
    
    // Sort Strings
    /**
     * A String indicating the results should be sorted by Last Name then First Name
     */
    public static final String NAME_SORT_STRING = "Name";
    /**
     * A String indicating the results should be sorted by Username
     */
    public static final String USERNAME_SORT_STRING = "Username";
    /**
     * A String indicating the results should be sorted by Administrator
     */
    public static final String ADMIN_SORT_STRING = "Administrator";
    /**
     * A String indicating the results should be sorted by Email
     */
    public static final String EMAIL_SORT_STRING = "Email";
    /**
     * A String indicating the results should be sorted by Date Created
     */
    public static final String CREATED_SORT_STRING = "Created";
    /**
     * A String indicating the results should be sorted by Date last Modified
     */
    public static final String LAST_MODIFIED_SORT_STRING = "Last Modified";
    /**
     * A String indicating the results should be sorted by Activated status
     */
    public static final String ACTIVATED_SORT_STRING = "Activated";
    /**
     * A String indicating the results should be sorted by Locked status
     */
    public static final String LOCKED_SORT_STRING = "Locked";
    

    /**
     * The Default Sort Type
     */
    public static final String DEFAULT_SORT_STRING = NAME_SORT_STRING;
    
    public static final String NAME_URL_STRING = "name";
    public static final String USERNAME_URL_STRING = "username";
    public static final String ADMIN_URL_STRING = "admin";
    public static final String EMAIL_URL_STRING = "email";
    public static final String CREATED_URL_STRING = "created";
    public static final String LAST_MODIFIED_URL_STRING = "modified";
    public static final String ACTIVATED_URL_STRING = "activated";
    public static final String LOCKED_URL_STRING = "locked";
    
    /**
     */
    public static final int PASSWORD_LEN_MIN = 5;
    /**
     */
    public static final int PASSWORD_LEN_MAX = 16;
    
    /*
     * I'm not sure about putting this enum here, but it seems weird in other
     * places too. Since sort information is already here, in the *_SORT_STRING
     * constants, I think this is appropriate.
     */
    public enum SortType {
        NAME (NAME_URL_STRING, NAME_SORT_STRING),
        USERNAME (USERNAME_URL_STRING, USERNAME_SORT_STRING),
        ADMIN (ADMIN_URL_STRING, ADMIN_SORT_STRING),
        EMAIL (EMAIL_URL_STRING, EMAIL_SORT_STRING),
        CREATED (CREATED_URL_STRING, CREATED_SORT_STRING),
        LAST_MODIFIED (LAST_MODIFIED_URL_STRING, LAST_MODIFIED_SORT_STRING),
        ACTIVATED (ACTIVATED_URL_STRING, ACTIVATED_SORT_STRING),
        LOCKED (LOCKED_URL_STRING, LOCKED_SORT_STRING);

        private final String urlString;
        private final String titleString;

        SortType(String urlString, String titleString){
            this.urlString = urlString;
            this.titleString = titleString;
        }

        public String getTitleString() {
            return titleString;
        }

        public String getUrlString() {
            return urlString;
        }

        public static SortType getByUrlString(String string) {
            if (string.equals(NAME_URL_STRING)){
                return NAME;
            } else if (string.equals(USERNAME_URL_STRING)){
                return USERNAME;
            } else if (string.equals(ADMIN_URL_STRING)){
                return ADMIN;
            } else if (string.equals(EMAIL_URL_STRING)){
                return EMAIL;
            } else if (string.equals(CREATED_URL_STRING)){
                return CREATED;
            } else if (string.equals(LAST_MODIFIED_URL_STRING)){
                return LAST_MODIFIED;
            } else if (string.equals(ACTIVATED_URL_STRING)){
                return ACTIVATED;
            } else if (string.equals(LOCKED_URL_STRING)){
                return LOCKED;
            } else {
                return null;
            }
        }
    }
    
    /**
     */
    public String getUid();

    /**
     * @param uid
     */
    public void setUid(String uid);

    /**
     */
    public String getUsername();

    /**
     */
    public void setUsername(String username);

    /**
     */
    public String getOldUsername();

    /**
     */
    public boolean isUsernameChanged();

    /**
     */
    public String getPassword();

    /**
     */
    public void setPassword(String password);

    /**
     */
    public String getFirstName();

    /**
     */
    public void setFirstName(String firstName);

    /**
     */
    public String getLastName();

    /**
     */
    public void setLastName(String lastName);

    /**
     */
    public String getEmail();

    /**
     */
    public void setEmail(String email);

    /**
     */
    public String getOldEmail();

    /**
     */
    public boolean isEmailChanged();

    /**
     */
    public Boolean getAdmin();

    public Boolean getOldAdmin();

    /**
     */
    public boolean isAdminChanged();

    /**
     */
    public void setAdmin(Boolean admin);

    /**
     */
    public String getActivationId();

    /**
     */
    public void setActivationId(String activationId);

    /**
     */
    public boolean isOverlord();

    /**
     */
    public boolean isActivated();

    /**
     *
     *
     */
    public void activate();

    public Boolean isLocked();

    public void setLocked(Boolean locked);

    /**
     */
    public void validateRawPassword();

    public Set<Preference> getPreferences();

    public void addPreference(Preference preference);

    public Preference getPreference(String key);

    public void removePreference(String key);

    public void removePreference(Preference preference);

    public Set<CollectionSubscription> getCollectionSubscriptions();

    public void addSubscription(CollectionSubscription subscription);

    /**
     * Get the CollectionSubscription with the specified displayName
     * @param displayname display name of subscription to return
     * @return subscription with specified display name
     */
    public CollectionSubscription getSubscription(String displayname);

    /**
     * Get the CollectionSubscription with the specified collectionUid 
     * and ticketKey
     * @param collectionUid collection uid of subscription to return
     * @param ticketKey ticketKey of subscription to return
     * @return subscription with specified collectionUid and ticketKey
     */
    public CollectionSubscription getSubscription(String collectionUid,
            String ticketKey);

    /**
     * Remove the CollectionSubscription with the specifed collectionUid and ticketKey
     * @param collectionUid collection uid of subscription to remove
     * @param ticketKey ticketKey of subscription to remove
     */
    public void removeSubscription(String collectionUid, String ticketKey);

    /**
     * Remove the CollectionSubscription with the specifed displayName
     * @param name display name of the subscription to remove
     */
    public void removeSubscription(String displayName);

    /** */
    public void removeSubscription(CollectionSubscription sub);

    /**
     * Return true if this user is subscribed to <code>collection</code>
     */
    public boolean isSubscribedTo(CollectionItem collection);

    public String calculateEntityTag();

}

cosmo/src/main/webapp/WEB-INF/jsp/home/collection.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" %>

<%--
/*
 * Copyright 2005-2007 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
--%>

<%@ include file="/WEB-INF/jsp/taglibs.jsp"  %>
<%@ include file="/WEB-INF/jsp/tagfiles.jsp" %>

<c:set var="ccstamp" value="${Collection.stampMap['calendar']}"/>
<c:if test="${ccstamp != null}">
  <c:url var="webcalUrl" value="/webcal/collection/${Collection.uid}/${Collection.displayName}.ics" />
  <c:url var="htmlUrl" value="/browse/view${Path}" />
</c:if>
<c:url var="feedUrl" value="/atom/collection/${Collection.uid}" />

<cosmo:standardLayout prefix="HomeDirectory.Collection." 
				      contentWrapperClass="fullPageWidthContent" stylesheets="account_browser"
				      parseWidgets="false">

<div>
  <span class="hd" style="margin-top: 12px;">
  <fmt:message key="HomeDirectory.Collection.Title">
      <fmt:param><c:out value="${Collection.displayName}"/></fmt:param>
  </fmt:message>
  </span>
  <span class="md"><c:out value="${Path}"/></span>
</div>

<div style="margin-top:12px;">
<c:if test="${ccstamp != null}">
<a href="${webcalUrl}">[download as iCalendar]</a>
<a href="${htmlUrl}">[view as HTML]</a>
</c:if>
<a href="${feedUrl}">[subscribe to feed]</a>
</div>

<div class="hd" style="margin-top: 12px;">
  Collection Properties
</div>

<div style="margin-top:12px;">
  <table cellpadding="3" cellspacing="1" border="0">
    <tr>
      <td class="mdLabel" style="text-align:right;">
        UID
      </td>
      <td class="mdData">
        <c:out value="${Collection.uid}"/>
      </td>
    </tr>
    <tr>
      <td class="mdLabel" style="text-align:right;">
        Created on Server:
      </td>
      <td class="mdData">
        <fmt:formatDate value="${Collection.creationDate}" type="both"/>
      </td>
    </tr>
    <tr>
      <td class="mdLabel" style="text-align:right;">
        Last Modified on Server:
      </td>
      <td class="mdData">
        <fmt:formatDate value="${Collection.modifiedDate}" type="both"/>
      </td>
    </tr>
  </table>
</div>

<c:if test="${ccstamp != null}">
<div class="hd" style="margin-top: 12px;">
  Calendar Properties
</div>

<div style="margin-top:12px;">
  <table cellpadding="3" cellspacing="1" border="0">
    <tr>
      <td class="mdLabel" style="text-align:right;">
        Description
      </td>
      <td class="mdData">
        <c:choose><c:when test="${ccstamp.description != null}"><c:out value="${ccstamp.description}"/></c:when><c:otherwise><span class="disabled">-</span></c:otherwise></c:choose>
      </td>
    </tr>
    <tr>
      <td class="mdLabel" style="text-align:right;">
        Language
      </td>
      <td class="mdData">
        <c:choose><c:when test="${ccstamp.language != null}"><c:out value="${ccstamp.language}"/></c:when><c:otherwise><span class="disabled">-</span></c:otherwise></c:choose>
      </td>
    </tr>
    <tr>
      <td class="mdLabel" style="text-align:right;">
        Timezone
      </td>
      <td class="mdData">
        <c:choose><c:when test="${ccstamp.timezoneName != null}"><c:out value="${ccstamp.timezoneName}"/></c:when><c:otherwise><span class="disabled">-</span></c:otherwise></c:choose>
      </td>
    </tr>
  </table>
</div>
</c:if>

<div class="hd" style="margin-top: 12px;">
  Contents
</div>

<div style="margin-top:12px;">
  <table cellpadding="4" cellspacing="1" border="0" width="100%">
    <tr>
      <td class="smTableColHead" style="width:1%;">
        &nbsp;
      </td>
      <td class="smTableColHead" style="text-align:left;">
        Name
      </td>
      <td class="smTableColHead">
        Type
      </td>
      <td class="smTableColHead">
        Created
      </td>
      <td class="smTableColHead">
        Last Modified
      </td>
      <td class="smTableColHead">
        Size
      </td>
    </tr>
    <c:forEach var="item" items="${Collection.children}">
      <c:choose><c:when test="${cosmoui:instanceOf('org.osaf.cosmo.model.NoteItem', item) &&  !empty item.modifies}"></c:when>
      <c:otherwise>
      
    <tr>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
      <a href='<c:url value="/browse${Path}/${item.name}" />'>[browse]</a>
        <c:if test="${item.parent != null}"><a href='<c:url value="/browse/remove${Path}/${item.name}" />'>[remove]</a></c:if>
      </td>
      <td class="smTableData">
        <c:out value="${item.displayName}"/>
      </td>
      <td class="smTableData" style="text-align:center;">
        <c:choose><c:when test="${item.parent == null}">Home</c:when><c:when test="${item.stampMap['calendar'] != null}">Calendar</c:when><c:when test="${cosmoui:instanceOf('org.osaf.cosmo.model.CollectionItem', item)}">Folder</c:when><c:when test="${item.stampMap['event'] != null}">Event</c:when><c:when test="${cosmoui:instanceOf('org.osaf.cosmo.model.FileItem', item)}">File</c:when><c:otherwise>Item</c:otherwise></c:choose>
      </td>
      <td class="smTableData" style="text-align:center;">         
        <fmt:formatDate value="${item.creationDate}" type="both"/>
      </td>
      <td class="smTableData" style="text-align:center;">
        <c:choose><c:when test="${cosmoui:instanceOf('org.osaf.cosmo.model.NoteItem', item)}"><fmt:formatDate value="${item.modifiedDate}" type="both"/></c:when><c:otherwise><span class="disabled">-</span></c:otherwise></c:choose>
      </td>
      <td class="smTableData" style="text-align:center;">
        <c:choose><c:when test="${cosmoui:instanceOf('org.osaf.cosmo.model.FileItem', item)}"><fmt:formatNumber value="${item.contentLength}"/> b</c:when><c:otherwise><span class="disabled">-</span></c:otherwise></c:choose>
      </td>
    </tr>
      </c:otherwise></c:choose>
    </c:forEach>
  </table>
</div>

<c:set var="item" value="${Collection}" scope="request"/>
<c:set var="path" value="${Path}" scope="request"/>
<c:set var="isCollection" value="true" scope="request"/>

<jsp:include page="inc-tickets.jsp" />

<jsp:include page="inc-attributes.jsp" />

<c:if test="${User != null}">
<div class="hd" style="margin-top: 12px;">
	Subscriptions
</div>
<div style="margin-top:12px;">

<!-- Display subscribed collections -->
  <table cellpadding="4" cellspacing="1" border="0" width="100%">
    <tr>
      <td class="smTableColHead" style="width:1%;">
        &nbsp;
      </td>
      <td class="smTableColHead" style="text-align:center;">
        Name
      </td>
      <td class="smTableColHead" style="text-align:center;">
        Collection Uid
      </td>
      <td class="smTableColHead" style="text-align:center;">
	 	Ticket
      </td>
      <td class="smTableColHead" style="text-align:center;">
		Created
      </td>
      <td class="smTableColHead" style="text-align:center;">
		Last Modified
      </td>
    </tr>
  <c:forEach var="subscription" items="${User.collectionSubscriptions}">
	<tr>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <a href="<c:url value="/browse/remove_subscription/${User.username}/${subscription.displayName}"/>">
        [remove]
        </a>
      </td>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <c:out value="${subscription.displayName}"/>
      </td>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <c:out value="${subscription.collectionUid}"/>
      </td>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <c:out value="${subscription.ticketKey}"/>
      </td>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <fmt:formatDate value="${subscription.creationDate}" type="both"/>
      </td>
      <td class="smTableData" style="text-align:center; white-space:nowrap;">
        <fmt:formatDate value="${subscription.modifiedDate}" type="both"/>
      </td>
    </tr>
  </c:forEach>
  </table>
</div>
</c:if>

</cosmo:standardLayout>

cosmo/src/main/webapp/WEB-INF/jsp/home/inc-attributes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" %>

<%--
/*
 * Copyright 2005-2007 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
--%>

<%@ include file="/WEB-INF/jsp/taglibs.jsp"  %>
<%@ include file="/WEB-INF/jsp/tagfiles.jsp" %>

<c:if test="${isCollection}">
  <c:set var="Item" value="${Collection}"/>
</c:if>

<div class="hd" style="margin-top: 12px;">
  Attributes
</div>

<div style="margin-top:12px;">
  <table cellpadding="4" cellspacing="1" border="0" width="100%">
    <tr>
       <td class="smTableColHead" style="text-align:left;">
        Namespace
      </td>
      <td class="smTableColHead" style="text-align:left;">
        Name
      </td>
      <td class="smTableColHead" style="text-align:left;">
        Value
      </td>
    </tr>
    <c:forEach var="attr" items="${Item.attributes}">
      <c:if test="${! fn:startsWith(attr.key.namespace, 'org.osaf.cosmo')}">
    <tr>
      <td class="smTableData" width="50%">
        <c:out value="${attr.key.namespace}"/>
      </td>
      <td class="smTableData" width="50%">
        <c:out value="${attr.key.localName}"/>
      </td>
      <td class="smTableData" width="50%">
        <c:out value="${attr.value.value}"/>
      </td>
    </tr>
      </c:if>
    </c:forEach>
  </table>
</div>

cosmo/src/main/webapp/WEB-INF/jsp/home/inc-indexes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" %>

<%--
/*
 * Copyright 2006 Open Source Applications Foundation
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
--%>

<%@ include file="/WEB-INF/jsp/taglibs.jsp"  %>
<%@ include file="/WEB-INF/jsp/tagfiles.jsp" %>

<c:choose>
  <c:when test="${not empty Item.stampMap['eventexception']}">
    <c:set var="index" value="${Item.stampMap['eventexception'].timeRangeIndex}"/>
  </c:when>
  <c:otherwise>
    <c:set var="index" value="${Item.stampMap['event'].timeRangeIndex}"/>
  </c:otherwise>
</c:choose>

<div class="hd" style="margin-top: 12px;">
  Time Range Index
</div>

<div style="margin-top:12px;">
  <table cellpadding="4" cellspacing="1" border="0" width="100%">
    <tr>
      <td class="smTableColHead" style="text-align:left;">
        Start Date
      </td>
      <td class="smTableColHead" style="text-align:left;">
        End Date
      </td>
      <td class="smTableColHead" style="text-align:left;">
        Floating?
      </td>
    </tr>
    <tr>
      <td class="smTableData" width="50%">
        <c:out value="${index.startDate}"/>
      </td>
      <td class="smTableData" width="50%">
        <c:out value="${index.endDate}"/>
      </td>
      <td class="smTableData" width="50%">
        <c:out value="${index.isFloating}"/>
      </td>
    </tr>
  </table>
</div>